name: Publish two versions

on:
  push:
    branches:
      - source

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Yarn install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Yarn build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
    
      - name: Prepare two language versions
        run: |
          cp -vr dist page-en && cp -vr dist page-zh
          cd page-en
          rm index.zh.html && mv index.en.html index.html
          cd ..
          cd page-zh
          rm index.en.html && mv index.zh.html index.html
          cd ..
          echo "Files are prepared."
          ls -lah dist page-en page-zh
    
      - name: Deploy Chinese version
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          REPOSITORY_NAME: moesoha/moesoha.github.io
          BRANCH: master
          FOLDER: page-zh
      - name: Deploy English version
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          REPOSITORY_NAME: moesoha/sohaj.in
          BRANCH: master
          FOLDER: page-en

