name: Publish two versions

on:
  push:
    branches:
      - source

jobs:
  deploy-zh:
    env:
      COMPILE_LANG: zh
      GOOGLE_ANALYTICS_ID: UA-83198456-4
      DEPLOY_DOMAIN: jin.sh
      GITHUB_REPOSITORY: moesoha/moesoha.github.io
    runs-on: ubuntu-latest
    steps:
      # Preparing
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Yarn install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      # clean up
      - name: Yarn clean
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: clean

      # Build and Deploy
      - name: Yarn build
        uses: borales/actions-yarn@v2.3.0
        env:
          NODE_ENV: production
        with:
          cmd: build
          
      - name: Write CNAME file
        run: |
          echo $DEPLOY_DOMAIN > dist/CNAME

      - name: Deploy pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository-name: ${{ env.GITHUB_REPOSITORY }}
          branch: master
          folder: dist

  deploy-en:
    env:
      COMPILE_LANG: en
      GOOGLE_ANALYTICS_ID: UA-83198456-3
      DEPLOY_DOMAIN: sohaj.in
      GITHUB_REPOSITORY: moesoha/sohaj.in
    # JUST SIMPLE COPY & PASTE BELOW SINCE GITHUB DID NOT SUPPORT ANCHORS
    runs-on: ubuntu-latest
    steps:
      # Preparing
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Yarn install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      # clean up
      - name: Yarn clean
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: clean

      # Build and Deploy
      - name: Yarn build
        uses: borales/actions-yarn@v2.3.0
        env:
          NODE_ENV: production
        with:
          cmd: build
          
      - name: Write CNAME file
        run: |
          echo $DEPLOY_DOMAIN > dist/CNAME

      - name: Deploy pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository-name: ${{ env.GITHUB_REPOSITORY }}
          branch: master
          folder: dist